// make_spirv - compiles the Vulkan engine's shaders to SPIR-V, into spirv_filters.h.
//
//     make_spirv <glslang.exe> <output header>
//
// Vulkan takes nothing but SPIR-V, and nothing that ships with Windows or Visual Studio makes it
// (the Windows SDK's dxc is built without it), so the shaders are compiled once, here, by
// Khronos's glslang, and the result is a header: the exe needs no compiler, and nobody building
// it does either - only someone changing a shader, who runs shaders\build_spirv.bat.
//
// The sources are glsl_filters.h's, the same GLSL the OpenGL engine compiles at run time, behind
// the Vulkan header (VulkanShaderSourceAt). The header written records the hash of every piece
// each shader came from and static_asserts them against glsl_filters.h, so the two cannot drift
// apart without the build saying so.

#include "glsl_filters.h"

#include <cstdio>
#include <cstdlib>
#include <string>
#include <vector>

using namespace psxemu;

namespace {

    bool WriteText(const std::string& path, const std::string& text) {
        FILE* f = fopen(path.c_str(), "wb");
        if (f == nullptr)
            return false;
        fwrite(text.data(), 1, text.size(), f);
        fclose(f);
        return true;
    }

    bool ReadWords(const std::string& path, std::vector<uint32_t>* words) {
        FILE* f = fopen(path.c_str(), "rb");
        if (f == nullptr)
            return false;
        fseek(f, 0, SEEK_END);
        const long size = ftell(f);
        fseek(f, 0, SEEK_SET);
        if (size <= 0 || size % 4 != 0) {
            fclose(f);
            return false;
        }
        words->resize(static_cast<size_t>(size) / 4);
        const size_t read = fread(words->data(), 4, words->size(), f);
        fclose(f);
        return read == words->size();
    }

    std::string Identifier(const char* key) {
        std::string out = "kSpirv_";
        for (const char* c = key; *c != 0; ++c)
            out += (isalnum(static_cast<unsigned char>(*c)) != 0) ? *c : '_';
        return out;
    }

}   // namespace

int main(int argc, char** argv) {
    if (argc != 3) {
        fprintf(stderr, "usage: make_spirv <glslang.exe> <output header>\n");
        return 2;
    }
    const std::string glslang = argv[1];
    const std::string output = argv[2];

    std::string arrays;
    std::string table;
    std::string checks;
    for (size_t i = 0; i < kVulkanShaderCount; ++i) {
        const VulkanShaderSource source = VulkanShaderSourceAt(i);
        std::string text;
        for (const char* part : source.parts) {
            if (part != nullptr)
                text += part;
        }
        const bool vertex = i == 0;
        const std::string stem = std::string("make_spirv_") + source.key;
        const std::string glsl = stem + (vertex ? ".vert" : ".frag");
        const std::string spv = stem + ".spv";
        if (!WriteText(glsl, text)) {
            fprintf(stderr, "could not write %s\n", glsl.c_str());
            return 1;
        }
        // -V: SPIR-V for Vulkan. -g0: no debug names, a sixth of the size and nothing
        // the driver needs. Quiet unless it fails.
        const std::string command =
            "\"\"" + glslang + "\" -V -g0 --quiet \"" + glsl + "\" -o \"" + spv + "\"\"";
        if (system(command.c_str()) != 0) {
            fprintf(stderr, "glslang failed on %s (%s)\n", source.key, glsl.c_str());
            return 1;
        }
        std::vector<uint32_t> words;
        if (!ReadWords(spv, &words) || words.empty() || words[0] != 0x07230203u) {
            fprintf(stderr, "no SPIR-V from %s\n", source.key);
            return 1;
        }
        remove(glsl.c_str());
        remove(spv.c_str());

        const std::string name = Identifier(source.key);
        char line[128];
        arrays += "    inline constexpr uint32_t " + name + "[] = {";
        for (size_t w = 0; w < words.size(); ++w) {
            snprintf(line, sizeof(line), "%s0x%08x,", (w % 8 == 0) ? "\n        " : " ",
                     words[w]);
            arrays += line;
        }
        arrays += "\n    };\n\n";

        table += "        { \"" + std::string(source.key) + "\", " + name + ", std::size(" + name +
                 ") },\n";
        for (int p = 0; p < 4; ++p) {
            snprintf(line, sizeof(line), "0x%016llxull",
                     static_cast<unsigned long long>(ShaderSourceHash(source.parts[p])));
            checks += "    static_assert(ShaderSourceHash(VulkanShaderSourceAt(" +
                      std::to_string(i) + ").parts[" + std::to_string(p) + "]) == " + line +
                      ", kSpirvStale);\n";
        }
        printf("%-16s %6zu words\n", source.key, words.size());
    }

    std::string header;
    header += "// Generated by shaders/make_spirv.cpp from glsl_filters.h with glslang - do not edit.\n";
    header += "// Rebuild it with shaders\\build_spirv.bat <path to glslang.exe> after changing a filter.\n";
    header += "#pragma once\n\n#include \"glsl_filters.h\"\n\n#include <cstddef>\n#include <cstdint>\n";
    header += "#include <iterator>\n\nnamespace psxemu {\n\n";
    header += arrays;
    header += "    // In VulkanShaderSourceAt order.\n";
    header += "    struct SpirvShader {\n        const char* key;\n        const uint32_t* code;\n";
    header += "        size_t words;\n    };\n\n";
    header += "    inline constexpr SpirvShader kSpirvShaders[] = {\n" + table + "    };\n";
    header += "    static_assert(std::size(kSpirvShaders) == kVulkanShaderCount,\n";
    header += "                  \"spirv_filters.h is older than glsl_filters.h: run shaders\\\\build_spirv.bat\");\n\n";
    header += "    // Every piece of GLSL each shader was compiled from, as it was then.\n";
    header += "#define kSpirvStale \"spirv_filters.h is older than glsl_filters.h: run shaders\\\\build_spirv.bat\"\n";
    header += checks;
    header += "#undef kSpirvStale\n\n}   // namespace psxemu\n";
    if (!WriteText(output, header)) {
        fprintf(stderr, "could not write %s\n", output.c_str());
        return 1;
    }
    printf("wrote %s\n", output.c_str());
    return 0;
}
